INFO:2025-07-21 10:58:00,441:MainThread:Dhan.py  started system
INFO:2025-07-21 10:58:00,442:MainThread:STARTED THE PROGRAM
WARNING:2025-07-21 10:58:07,606:MainThread:Certificate did not match expected hostname: api.dhan.co. Certificate: {'subject': ((('commonName', '*.alive.ap-south-1.prod.deploys.brightcove.com'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Amazon'),), (('commonName', 'Amazon RSA 2048 M04'),)), 'version': 3, 'serialNumber': '0E268A15CEC3CBEA5960C4D1C559DE68', 'notBefore': 'May 26 00:00:00 2025 GMT', 'notAfter': 'Jun 22 23:59:59 2026 GMT', 'subjectAltName': (('DNS', '*.alive.ap-south-1.prod.deploys.brightcove.com'), ('DNS', '*.pr.bcovlive.com'), ('DNS', '*.ap-south-1.pr.bcovlive.com')), 'OCSP': ('http://ocsp.r2m04.amazontrust.com',), 'caIssuers': ('http://crt.r2m04.amazontrust.com/r2m04.cer',), 'crlDistributionPoints': ('http://crl.r2m04.amazontrust.com/r2m04.crl',)}
ERROR:2025-07-21 10:58:07,607:MainThread:Exception in dhanhq>>intraday_history_minute_charts: HTTPSConnectionPool(host='api.dhan.co', port=443): Max retries exceeded with url: /v2/charts/historical (Caused by SSLError(CertificateError("hostname 'api.dhan.co' doesn't match either of '*.alive.ap-south-1.prod.deploys.brightcove.com', '*.pr.bcovlive.com', '*.ap-south-1.pr.bcovlive.com'")))
INFO:2025-07-21 11:00:14,530:MainThread:Dhan.py  started system
INFO:2025-07-21 11:00:14,531:MainThread:STARTED THE PROGRAM
INFO:2025-07-21 11:00:50,245:MainThread:Dhan.py  started system
INFO:2025-07-21 11:00:50,246:MainThread:STARTED THE PROGRAM
INFO:2025-07-21 11:19:33,888:MainThread:Dhan.py  started system
INFO:2025-07-21 11:19:33,888:MainThread:STARTED THE PROGRAM
INFO:2025-07-21 11:21:41,245:MainThread:Dhan.py  started system
INFO:2025-07-21 11:21:41,246:MainThread:STARTED THE PROGRAM
ERROR:2025-07-21 11:22:24,780:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "d:\AI Trading\VS Project\Trading\Dhan_Tradehull.py", line 571, in get_intraday_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
INFO:2025-07-21 11:45:18,196:MainThread:Dhan.py  started system
INFO:2025-07-21 11:45:18,197:MainThread:STARTED THE PROGRAM
WARNING:2025-07-21 11:45:19,238:MainThread:Certificate did not match expected hostname: api.dhan.co. Certificate: {'subject': ((('commonName', '*.getprolist.com'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Amazon'),), (('commonName', 'Amazon RSA 2048 M04'),)), 'version': 3, 'serialNumber': '0A802CE598C63D4D12569689A63396F4', 'notBefore': 'May 13 00:00:00 2025 GMT', 'notAfter': 'Jun 11 23:59:59 2026 GMT', 'subjectAltName': (('DNS', '*.getprolist.com'), ('DNS', 'getprolist.com')), 'OCSP': ('http://ocsp.r2m04.amazontrust.com',), 'caIssuers': ('http://crt.r2m04.amazontrust.com/r2m04.cer',), 'crlDistributionPoints': ('http://crl.r2m04.amazontrust.com/r2m04.crl',)}
ERROR:2025-07-21 11:45:19,238:MainThread:Exception in dhanhq>>intraday_history_minute_charts: HTTPSConnectionPool(host='api.dhan.co', port=443): Max retries exceeded with url: /v2/charts/historical (Caused by SSLError(CertificateError("hostname 'api.dhan.co' doesn't match either of '*.getprolist.com', 'getprolist.com'")))
ERROR:2025-07-21 11:45:25,556:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-902', 'error_type': 'Invalid_Access', 'error_message': 'HTTP Status 451. User has not subscribed to Data APIs or does not have access to Trading APIs. Kindly subscribe to Data APIs to be able to fetch Data.'}, 'data': {'errorType': 'Invalid_Access', 'errorCode': 'DH-902', 'errorMessage': 'HTTP Status 451. User has not subscribed to Data APIs or does not have access to Trading APIs. Kindly subscribe to Data APIs to be able to fetch Data.'}}
Traceback (most recent call last):
  File "d:\AI Trading\VS Project\Trading\Dhan_Tradehull.py", line 571, in get_intraday_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-902', 'error_type': 'Invalid_Access', 'error_message': 'HTTP Status 451. User has not subscribed to Data APIs or does not have access to Trading APIs. Kindly subscribe to Data APIs to be able to fetch Data.'}, 'data': {'errorType': 'Invalid_Access', 'errorCode': 'DH-902', 'errorMessage': 'HTTP Status 451. User has not subscribed to Data APIs or does not have access to Trading APIs. Kindly subscribe to Data APIs to be able to fetch Data.'}}
INFO:2025-07-21 11:53:15,113:MainThread:Dhan.py  started system
INFO:2025-07-21 11:53:15,114:MainThread:STARTED THE PROGRAM
ERROR:2025-07-21 11:53:37,451:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-905', 'error_type': 'Input_Exception', 'error_message': 'System is unable to fetch data due to incorrect parameters or no data present'}, 'data': {'errorType': 'Input_Exception', 'errorCode': 'DH-905', 'errorMessage': 'System is unable to fetch data due to incorrect parameters or no data present'}}
Traceback (most recent call last):
  File "d:\AI Trading\VS Project\Trading\Dhan_Tradehull.py", line 571, in get_intraday_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-905', 'error_type': 'Input_Exception', 'error_message': 'System is unable to fetch data due to incorrect parameters or no data present'}, 'data': {'errorType': 'Input_Exception', 'errorCode': 'DH-905', 'errorMessage': 'System is unable to fetch data due to incorrect parameters or no data present'}}
INFO:2025-07-21 12:00:12,746:MainThread:Dhan.py  started system
INFO:2025-07-21 12:00:12,747:MainThread:STARTED THE PROGRAM
ERROR:2025-07-21 12:01:33,541:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-905', 'error_type': 'Input_Exception', 'error_message': 'System is unable to fetch data due to incorrect parameters or no data present'}, 'data': {'errorType': 'Input_Exception', 'errorCode': 'DH-905', 'errorMessage': 'System is unable to fetch data due to incorrect parameters or no data present'}}
Traceback (most recent call last):
  File "d:\AI Trading\VS Project\Trading\Dhan_Tradehull.py", line 571, in get_intraday_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-905', 'error_type': 'Input_Exception', 'error_message': 'System is unable to fetch data due to incorrect parameters or no data present'}, 'data': {'errorType': 'Input_Exception', 'errorCode': 'DH-905', 'errorMessage': 'System is unable to fetch data due to incorrect parameters or no data present'}}
INFO:2025-07-21 12:04:20,881:MainThread:Dhan.py  started system
INFO:2025-07-21 12:04:20,882:MainThread:STARTED THE PROGRAM
WARNING:2025-07-21 12:05:04,015:MainThread:Certificate did not match expected hostname: api.dhan.co. Certificate: {'subject': ((('commonName', '*.ap-south-1.es.amazonaws.com'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Amazon'),), (('commonName', 'Amazon RSA 2048 M03'),)), 'version': 3, 'serialNumber': '0C6090FA9DB8632773256685C083FAFB', 'notBefore': 'Dec 19 00:00:00 2024 GMT', 'notAfter': 'Jan 17 23:59:59 2026 GMT', 'subjectAltName': (('DNS', '*.ap-south-1.es.amazonaws.com'),), 'OCSP': ('http://ocsp.r2m03.amazontrust.com',), 'caIssuers': ('http://crt.r2m03.amazontrust.com/r2m03.cer',), 'crlDistributionPoints': ('http://crl.r2m03.amazontrust.com/r2m03.crl',)}
ERROR:2025-07-21 12:05:04,016:MainThread:Exception in dhanhq>>intraday_history_minute_charts: HTTPSConnectionPool(host='api.dhan.co', port=443): Max retries exceeded with url: /v2/charts/historical (Caused by SSLError(CertificateError("hostname 'api.dhan.co' doesn't match '*.ap-south-1.es.amazonaws.com'")))
INFO:2025-07-21 12:12:52,768:MainThread:Dhan.py  started system
INFO:2025-07-21 12:12:52,769:MainThread:STARTED THE PROGRAM
ERROR:2025-07-21 12:13:20,880:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-905', 'error_type': 'Input_Exception', 'error_message': 'System is unable to fetch data due to incorrect parameters or no data present'}, 'data': {'errorType': 'Input_Exception', 'errorCode': 'DH-905', 'errorMessage': 'System is unable to fetch data due to incorrect parameters or no data present'}}
Traceback (most recent call last):
  File "d:\AI Trading\VS Project\Trading\Dhan_Tradehull.py", line 571, in get_intraday_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-905', 'error_type': 'Input_Exception', 'error_message': 'System is unable to fetch data due to incorrect parameters or no data present'}, 'data': {'errorType': 'Input_Exception', 'errorCode': 'DH-905', 'errorMessage': 'System is unable to fetch data due to incorrect parameters or no data present'}}
INFO:2025-07-21 12:16:54,458:MainThread:Dhan.py  started system
INFO:2025-07-21 12:16:54,458:MainThread:STARTED THE PROGRAM
INFO:2025-07-21 12:19:13,099:MainThread:Dhan.py  started system
INFO:2025-07-21 12:19:13,100:MainThread:STARTED THE PROGRAM
WARNING:2025-07-21 12:19:14,152:MainThread:Certificate did not match expected hostname: api.dhan.co. Certificate: {'subject': ((('commonName', '*.alive.ap-south-1.prod.deploys.brightcove.com'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Amazon'),), (('commonName', 'Amazon RSA 2048 M04'),)), 'version': 3, 'serialNumber': '0E268A15CEC3CBEA5960C4D1C559DE68', 'notBefore': 'May 26 00:00:00 2025 GMT', 'notAfter': 'Jun 22 23:59:59 2026 GMT', 'subjectAltName': (('DNS', '*.alive.ap-south-1.prod.deploys.brightcove.com'), ('DNS', '*.pr.bcovlive.com'), ('DNS', '*.ap-south-1.pr.bcovlive.com')), 'OCSP': ('http://ocsp.r2m04.amazontrust.com',), 'caIssuers': ('http://crt.r2m04.amazontrust.com/r2m04.cer',), 'crlDistributionPoints': ('http://crl.r2m04.amazontrust.com/r2m04.crl',)}
ERROR:2025-07-21 12:19:14,153:MainThread:Exception in dhanhq>>intraday_history_minute_charts: HTTPSConnectionPool(host='api.dhan.co', port=443): Max retries exceeded with url: /v2/charts/historical (Caused by SSLError(CertificateError("hostname 'api.dhan.co' doesn't match either of '*.alive.ap-south-1.prod.deploys.brightcove.com', '*.pr.bcovlive.com', '*.ap-south-1.pr.bcovlive.com'")))
INFO:2025-07-21 12:20:31,079:MainThread:Dhan.py  started system
INFO:2025-07-21 12:20:31,080:MainThread:STARTED THE PROGRAM
ERROR:2025-07-21 12:21:05,664:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-905', 'error_type': 'Input_Exception', 'error_message': 'System is unable to fetch data due to incorrect parameters or no data present'}, 'data': {'errorType': 'Input_Exception', 'errorCode': 'DH-905', 'errorMessage': 'System is unable to fetch data due to incorrect parameters or no data present'}}
Traceback (most recent call last):
  File "d:\AI Trading\VS Project\Trading\Dhan_Tradehull.py", line 571, in get_intraday_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-905', 'error_type': 'Input_Exception', 'error_message': 'System is unable to fetch data due to incorrect parameters or no data present'}, 'data': {'errorType': 'Input_Exception', 'errorCode': 'DH-905', 'errorMessage': 'System is unable to fetch data due to incorrect parameters or no data present'}}
INFO:2025-07-21 13:03:01,668:MainThread:Dhan.py  started system
INFO:2025-07-21 13:03:01,669:MainThread:STARTED THE PROGRAM
INFO:2025-07-21 13:15:41,902:MainThread:Dhan.py  started system
INFO:2025-07-21 13:15:41,903:MainThread:STARTED THE PROGRAM
